<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>LoadOrderKeeper</RootNamespace>
    <AssemblyName>StarfieldLoadOrderKeeper</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Title>Starfield Load Order Keeper</Title>
    <Copyright>MIT License</Copyright>
    <PackageProjectUrl>https://github.com/Mistralys/starfield-load-order-manager</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>git@github.com:Mistralys/starfield-load-order-manager.git</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <ApplicationIcon>Docs\Design\Favicon\icon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\dependabot.yml" />
    <None Include=".github\workflows\release.yml" />
    <None Include="installer\StarfieldLoadOrderKeeper.wixproj" />
    <None Include="Tests\LoadOrderKeeper.Tests\LoadOrderKeeper.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Gameloop.Vdf" Version="0.6.2" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Page Remove="Tests\**\*.xaml" />
    <None Remove="Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Docs\Design\Favicon\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\AboutViewResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AboutViewResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\CommentInputResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommentInputResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\CommonResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommonResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ConfirmationDialogResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConfirmationDialogResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\DiffDialogResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DiffDialogResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ErrorDialogResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ErrorDialogResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MainWindowResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MainWindowResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ManageProfilesResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ManageProfilesResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MenuViewResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MenuViewResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ProfilePropertiesResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProfilePropertiesResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ReferenceHistoryResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReferenceHistoryResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SettingsWindowResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SettingsWindowResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\SwitchProfileResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SwitchProfileResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\UpdateOptionsResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UpdateOptionsResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\ViewPendingChangesResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ViewPendingChangesResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AboutViewResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\AboutViewResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\AboutViewResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AboutViewResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommentInputResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommentInputResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommentInputResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommentInputResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ConfirmationDialogResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ConfirmationDialogResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ConfirmationDialogResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ConfirmationDialogResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DiffDialogResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DiffDialogResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\DiffDialogResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>DiffDialogResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorDialogResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorDialogResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ErrorDialogResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ErrorDialogResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MainWindowResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ManageProfilesResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ManageProfilesResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ManageProfilesResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ManageProfilesResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MenuViewResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MenuViewResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MenuViewResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MenuViewResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProfilePropertiesResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProfilePropertiesResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ProfilePropertiesResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProfilePropertiesResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ReferenceHistoryResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ReferenceHistoryResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ReferenceHistoryResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ReferenceHistoryResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SettingsWindowResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SettingsWindowResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SettingsWindowResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SettingsWindowResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SwitchProfileResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SwitchProfileResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\SwitchProfileResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SwitchProfileResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\UpdateOptionsResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\UpdateOptionsResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\UpdateOptionsResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UpdateOptionsResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewPendingChangesResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewPendingChangesResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\ViewPendingChangesResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ViewPendingChangesResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
