<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>LoadOrderKeeper</RootNamespace>
    <AssemblyName>StarfieldLoadOrderKeeper</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Title>Starfield Load Order Keeper</Title>
    <Copyright>MIT License</Copyright>
    <PackageProjectUrl>https://github.com/Mistralys/starfield-load-order-manager</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>git@github.com:Mistralys/starfield-load-order-manager.git</RepositoryUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <ApplicationIcon>Docs\Design\Favicon\icon.ico</ApplicationIcon>
    <Version>1.4.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\dependabot.yml" />
    <None Include=".github\workflows\release.yml" />
    <None Include="installer\StarfieldLoadOrderKeeper.wixproj" />
    <None Include="Tests\LoadOrderKeeper.Tests\LoadOrderKeeper.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Gameloop.Vdf" Version="0.6.2" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Page Remove="Tests\**\*.xaml" />
    <None Remove="Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Docs\Design\Favicon\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\AboutWindowResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>AboutWindowResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\CommonResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommonResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\MainWindowResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MainWindowResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\AboutWindowResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\AboutWindowResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\AboutWindowResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>AboutWindowResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\CommonResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommonResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.de.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.fr.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MainWindowResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>MainWindowResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
