//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadOrderKeeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindowResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindowResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoadOrderKeeper.Resources.MainWindowResources", typeof(MainWindowResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About....
        /// </summary>
        public static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Profile: .
        /// </summary>
        public static string ActiveProfilePrefixText {
            get {
                return ResourceManager.GetString("ActiveProfilePrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _Updates....
        /// </summary>
        public static string CheckForUpdatesMenuText {
            get {
                return ResourceManager.GetString("CheckForUpdatesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path configuration error, please review the configured paths..
        /// </summary>
        public static string ConfigErrorBannerText {
            get {
                return ResourceManager.GetString("ConfigErrorBannerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Debug.
        /// </summary>
        public static string DebugMenuHeader {
            get {
                return ResourceManager.GetString("DebugMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string DismissTooltip {
            get {
                return ResourceManager.GetString("DismissTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download options....
        /// </summary>
        public static string DownloadOptionsButtonText {
            get {
                return ResourceManager.GetString("DownloadOptionsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenuHeader {
            get {
                return ResourceManager.GetString("EditMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string ExitMenuText {
            get {
                return ResourceManager.GetString("ExitMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenuHeader {
            get {
                return ResourceManager.GetString("FileMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Manage Profiles....
        /// </summary>
        public static string ManageProfilesMenuText {
            get {
                return ResourceManager.GetString("ManageProfilesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _AppData Folder.
        /// </summary>
        public static string OpenAppDataFolderMenuText {
            get {
                return ResourceManager.GetString("OpenAppDataFolderMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Configuration Folder.
        /// </summary>
        public static string OpenConfigFolderMenuText {
            get {
                return ResourceManager.GetString("OpenConfigFolderMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Game Folder.
        /// </summary>
        public static string OpenGameFolderMenuText {
            get {
                return ResourceManager.GetString("OpenGameFolderMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Plugins.txt.
        /// </summary>
        public static string OpenPluginsMenuText {
            get {
                return ResourceManager.GetString("OpenPluginsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Reference File.
        /// </summary>
        public static string OpenReferenceMenuText {
            get {
                return ResourceManager.GetString("OpenReferenceMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string OpenSettingsButtonText {
            get {
                return ResourceManager.GetString("OpenSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play (SFSE).
        /// </summary>
        public static string PlayButtonSfse {
            get {
                return ResourceManager.GetString("PlayButtonSfse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play (Vanilla).
        /// </summary>
        public static string PlayButtonVanilla {
            get {
                return ResourceManager.GetString("PlayButtonVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.txt was modified outside Load Order Keeper..
        /// </summary>
        public static string PluginsModifiedWarningText {
            get {
                return ResourceManager.GetString("PluginsModifiedWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Profile.
        /// </summary>
        public static string ProfileMenuHeader {
            get {
                return ResourceManager.GetString("ProfileMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Status Messages:.
        /// </summary>
        public static string RecentStatusMessagesText {
            get {
                return ResourceManager.GetString("RecentStatusMessagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of changes....
        /// </summary>
        public static string ReferenceHistoryMenuText {
            get {
                return ResourceManager.GetString("ReferenceHistoryMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Configuration (for testing)....
        /// </summary>
        public static string ResetConfigMenuText {
            get {
                return ResourceManager.GetString("ResetConfigMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Settings....
        /// </summary>
        public static string SettingsMenuText {
            get {
                return ResourceManager.GetString("SettingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage load order.
        /// </summary>
        public static string ShowChangesButtonText {
            get {
                return ResourceManager.GetString("ShowChangesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage load order ({0} changes).
        /// </summary>
        public static string ShowChangesButtonTextWithCount {
            get {
                return ResourceManager.GetString("ShowChangesButtonTextWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Switch Profile....
        /// </summary>
        public static string SwitchProfileMenuText {
            get {
                return ResourceManager.GetString("SwitchProfileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Throw Test Exception.
        /// </summary>
        public static string ThrowTestExceptionMenuText {
            get {
                return ResourceManager.GetString("ThrowTestExceptionMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} is available!.
        /// </summary>
        public static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View Pending Changes....
        /// </summary>
        public static string ViewPendingChangesMenuText {
            get {
                return ResourceManager.GetString("ViewPendingChangesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starfield Load Order Keeper v{0}.
        /// </summary>
        public static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
    }
}
