//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarfieldLoadOrderManager.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class ManagerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ManagerSettings defaultInstance = ((ManagerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ManagerSettings())));
        
        public static ManagerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StarfieldFolder {
            get {
                return ((string)(this["StarfieldFolder"]));
            }
            set {
                this["StarfieldFolder"] = value;
            }
        }
    }
}
