//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadOrderKeeper.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_History {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_History() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoadOrderKeeper.Resources.Strings_History", typeof(Strings_History).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept the changes to confirm the switch..
        /// </summary>
        internal static string MSG_ApplyToConfirm {
            get {
                return ResourceManager.GetString("MSG_ApplyToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will then have the opportunity to review the changes before accepting them..
        /// </summary>
        internal static string MSG_OpportunityToReview {
            get {
                return ResourceManager.GetString("MSG_OpportunityToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled back to version {0}..
        /// </summary>
        internal static string MSG_RolledBackToVersionX {
            get {
                return ResourceManager.GetString("MSG_RolledBackToVersionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to rollback to version {0}?.
        /// </summary>
        internal static string MSG_SureToSwitchToVersionX {
            get {
                return ResourceManager.GetString("MSG_SureToSwitchToVersionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current mod list will be replaced with the list from version {0}..
        /// </summary>
        internal static string MSG_WillReplaceWithVersionX {
            get {
                return ResourceManager.GetString("MSG_WillReplaceWithVersionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback Confirmation.
        /// </summary>
        internal static string Title_RollbackConfirmation {
            get {
                return ResourceManager.GetString("Title_RollbackConfirmation", resourceCulture);
            }
        }
    }
}
